
POST http://localhost:3001/api/mails
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYyYTcxYTJmNjhiMjU4OWFkN2M3MmViMSIsImlhdCI6MTY1NTM3MTY2NiwiZXhwIjoxNjU1OTc2NDY2fQ.BtCzjB5rOkzF9szupiNCVDoycXFqbj37hPZPQzEt1jw

{
  "user": "62a71a2f68b2589ad7c72eb1",
  "ownerName": "String",
  "recipient": "62a6324bd922a35d9ea0e88d",
  "ownerWisible": true,
  "recipientWisible": true,
  "ownerPhotoMin": "String",
  "text": "String",
  "type": "String"
}
###

delete http://localhost:3001/api/mails/62a86b74a22df264fbcfc229
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYyYTcxYTJmNjhiMjU4OWFkN2M3MmViMSIsImlhdCI6MTY1NTIwODMxMSwiZXhwIjoxNjU1ODEzMTExfQ.-9zU11ELH0m6vjdvwX6KK7HyZ0208ABMOoioEAU1W00


