GET http://localhost:3001/api/personal

###
GET http://localhost:3001/api/personal?gender=all&raitingFrom=0&raitingTo=100

###

GET http://localhost:3001/api/personal/count?gender=man

###

POST http://localhost:3001/api/personal
Content-Type: application/json

{
  "username": "test",
  "email": "test",
  "name": "test",
  "password": "test"
}