GET http://localhost:3001/api/user

###

POST http://localhost:3001/api/user/registration
Content-Type: application/json

{
  "username": "test",
  "email": "test",
  "name": "test",
  "password": "password"
}


###

DELETE  http://localhost:3001/api/user/62a617a58a454b6dea90b987
Content-Type: application/json

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

###

PUT http://localhost:3001/api/user/follow/62a6324bd922a35d9ea0e88d
Content-Type: application/json
Authorization: bearer 


###

put  http://localhost:3001/api/users/unfollow/62a6324bd922a35d9ea0e88d
Content-Type: application/json
Authorization: bearer

{
  "username": "test",
  "password": "test"
}