GET http://localhost:3001/api/user

###

GET http://localhost:3001/api/user/me
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYyYTcxYTJmNjhiMjU4OWFkN2M3MmViMSIsImlhdCI6MTY1ODc1NDgxOCwiZXhwIjoxNjU5MzU5NjE4fQ.9y7wnzYM-YDDaK0W02tqis1omJeE-d2s4xYFNPzL40Q

###

POST http://localhost:3001/api/user/registration
Content-Type: application/json

{
  "username": "test",
  "email": "test",
  "name": "test",
  "password": "password"
}


###

DELETE  http://localhost:3001/api/user/62a617a58a454b6dea90b987
Content-Type: application/json

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

###

PUT http://localhost:3001/api/user/follow/62a6324bd922a35d9ea0e88d
Content-Type: application/json
Authorization: bearer 


###

put  http://localhost:3001/api/users/unfollow/62a6324bd922a35d9ea0e88d
Content-Type: application/json
Authorization: bearer

{
  "username": "test",
  "password": "test"
}